MISSION_START = datetime(2026, 6, 1, 8, 0, 0, 0); % 2026 June 01, 08:00:00.0
SIMULATION_END = MISSION_START + years(10); % CDS 14.1 maximum time to deorbit

SATELLITE_CATALOG_NUMBER = "00000";
ANNUAL_LAUNCH_NUMBER = "000";
LAUNCH_PIECE = "A  ";

ORBITAL_INCLINATION_DEG = 23.5;

initial_epoch_year = string(mod(year(MISSION_START), 100));
if (strlength(initial_epoch_year) == 1)
    initial_epoch_year = "0" + initial_epoch_year;
end
initial_epoch = day(MISSION_START, "dayofyear") + (second(MISSION_START, "secondofday") / 86400);

tle_file = fopen("temp/initial.tle", "w");
fprintf(tle_file, "%s\n", "RAPID-0");
fprintf(tle_file, "1 %sU %s%s%s %s%s %s %s %s 0 0001%d\n", ...
    SATELLITE_CATALOG_NUMBER, ...
    initial_epoch_year, ...
    ANNUAL_LAUNCH_NUMBER, ...
    LAUNCH_PIECE, ...
    initial_epoch_year, ...
    num2str(initial_epoch, 11), ...
    "-.00000000", ...
    "000000-0", ...
    "-10000-7", ...
    7 ...
);
fprintf(tle_file, "2 %s %s %s %s %s %s %s 00001%d\n", ...
    SATELLITE_CATALOG_NUMBER, ...
    "023.5000", ...% num2str(ORBITAL_INCLINATION_DEG, 8), ...
    "000.0000", ...
    "0000000", ...
    "000.0000", ...
    "000.0000", ...
    num2str(15.3882322768, 10), ... % orbits per day
    7 ...
);
fclose(tle_file);

disp(string(py.satellite_simulator.get_string()));

simulation = satelliteScenario(MISSION_START, SIMULATION_END, 1);
rapid_0_satellite = satellite(simulation, "temp/initial.tle", "Name", "satSGP4", "OrbitPropagator", "sgp4");
gs_ucla = groundStation(simulation, 34.069, -118.443, Name="UCLA");
sim_viewer = satelliteScenarioViewer(scenario);
